version: '3'
services:

  web:
    build: './web'
    restart: unless-stopped
    ports:
      - '80:3000'
    volumes:
      - './web/src:/app/src'

  api:
    build: './api'
    restart: unless-stopped
    ports:
      - '81:3000'
    volumes:
      - './api:/api'

  db:
    image: mongo
    restart: unless-stopped
    ports:
      - "5656:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password