version: '3'
services:

  web:
    build: './web'
    restart: unless-stopped
    ports:
      - '80:3000'
    volumes:
      - './web/src:/app/src'

  api:
    build: './api'
    restart: unless-stopped
    ports:
      - '81:3000'
      - '5000:5000'

  db:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: postdata